theme: osuny
_merge: deep
params:
  summary:
    position: hero
  search:
    active: true
  logo:
    header: '/assets/images/logo-color.svg'
    footer: '/assets/images/logo-white.svg'
  home:
    head:
      title: site