[[cors]]
allowed_origins = "*"
allowed_methods = ["GET", "POST"]
allowed_headers = "*"

[[headers]]
for = ["**/*.woff2", "**/*.woff", "**/*.svg", "**/*.ttf", "**/*.otf", "**/*.eot", "**/*.js", "**/*.css"]
compress = "gzip"
[headers.values]
Cache-Control = "max-age=31536000, no-transform, public"

[[headers]]
for = ["**/*.png", "**/*.jpg", "**/*.jpeg", "**/*.gif", "**/*.webp"]
[headers.values]
Cache-Control = "max-age=31536000, no-transform, public"

[[redirects]]
from = "/edition-2025/"
to = "/dernieres-editions/edition-2025/"

[[redirects]]
from = "/projets/thematique/biodiversite/"
to = "/reportages/thematique/biodiversite/"

[[redirects]]
from = "/projets/concours-et-prix/concours-general/"
to = "/reportages/concours-et-prix/concours-general/"

[[redirects]]
from = "/organisations/"
to = "/soutiens-et-partenaires/"

[[redirects]]
from = "/organisations/categories/institutionnels-financiers/"
to = "/soutiens-et-partenaires/categories/institutionnels-financiers/"

[[redirects]]
from = "/projets/concours-et-prix/"
to = "/reportages/concours-et-prix/"

[[redirects]]
from = "/organisations/ademe/"
to = "/soutiens-et-partenaires/ademe/"

[[redirects]]
from = "/projets/thematique/"
to = "/reportages/thematique/"

[[redirects]]
from = "/organisations/categories/techniques/"
to = "/soutiens-et-partenaires/categories/techniques/"

[[redirects]]
from = "/organisations/agence-francaise-de-developpement/"
to = "/soutiens-et-partenaires/agence-francaise-de-developpement/"

[[redirects]]
from = "/projets/categories/19-25-ans-filiere-journalisme/"
to = "/reportages/categories/19-25-ans-filiere-journalisme/"

[[redirects]]
from = "/qui-sommes-nous/"
to = "/presentation/qui-sommes-nous/"

[[redirects]]
from = "/organisations/office-francais-de-la-biodiversite/"
to = "/soutiens-et-partenaires/office-francais-de-la-biodiversite/"

[[redirects]]
from = "/projets/reportages/"
to = "/reportages/reportages/"

[[redirects]]
from = "/le-concours/"
to = "/presentation/le-concours/"

[[redirects]]
from = "/projets/thematique/alimentation/"
to = "/reportages/thematique/alimentation/"

[[redirects]]
from = "/projets/2025-au-restaurant-etoile-de-nieuwe-winkel-la-gastronomie-botanique-pour-sauver-la-planete/"
to = "/reportages/2025-au-restaurant-etoile-de-nieuwe-winkel-la-gastronomie-botanique-pour-sauver-la-planete/"

[[redirects]]
from = "/projets/"
to = "/reportages/"

[[redirects]]
from = "/projets/categories/19-25-ans-hors-filiere-journalisme/"
to = "/reportages/categories/19-25-ans-hors-filiere-journalisme/"

[[redirects]]
from = "/projets/categories/"
to = "/reportages/categories/"

[[redirects]]
from = "/projets/reportages/video/"
to = "/reportages/reportages/video/"

[[redirects]]
from = "/projets/2025-une-ile-paradisiaque-menacee-par-des-chevres-un-defi-ecologique/"
to = "/reportages/2025-une-ile-paradisiaque-menacee-par-des-chevres-un-defi-ecologique/"

